name: Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEVELOPMENT_EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.DEVELOPMENT_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Execute script on EC2
        run: |
          ssh ${{ secrets.DEVELOPMENT_EC2_USER }}@${{ secrets.DEVELOPMENT_EC2_HOST }} << EOF
          # Commands to run on the EC2 instance
          cd thesru_backend
          git checkout development
          git pull
          docker system prune -a -f
          docker compose up -d --build --force-recreate --remove-orphans || true
          docker buildx build --platform linux/arm64 -t thesru-backend:development-latest --load .
          docker stop thesru-backend || true
          docker rm thesru-backend || true
          docker run -d --name thesru-backend --env-file .env --network=thesru_backend_thesru -p 6000:8000 thesru-backend:development-latest
          EOF
