name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Execute script on EC2
        run: |
          ssh ${{ secrets.PRODUCTION_EC2_USER }}@${{ secrets.PRODUCTION_EC2_HOST }} << EOF
          # Commands to run on the EC2 instance
          cd schoolfirst-backend
          git checkout master
          git pull
          docker system prune -a -f
          # docker compose up -d --build --force-recreate --remove-orphans || true
          docker buildx build --platform linux/arm64 -t schoolfirst-backend:master-latest --load .
          docker stop schoolfirst-backend || true
          docker rm schoolfirst-backend || true
          docker run -d --name schoolfirst-backend --env-file .env -p 8000:8000 schoolfirst-backend:master-latest
          EOF
