name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Execute script on EC2
        run: |
          ssh ${{ secrets.PRODUCTION_EC2_USER }}@${{ secrets.PRODUCTION_EC2_HOST }} << EOF
          # Commands to run on the EC2 instance
          cd thesru_backend
          git checkout main
          git pull
          docker system prune -a -f
          docker buildx build --platform linux/arm64 -t thesru-backend:main-latest --load .
          docker stop thesru-backend || true
          docker rm thesru-backend || true
          docker run -d --name thesru-backend --env-file .env -p 6000:8000 thesru-backend:main-latest
          EOF
